### ISSUE TITLE
run error!

### ISSUE THREAD

**Issue by ZhouAo-ZA** [phython96/GNAS-MP#1]
when i try to run the sh scripts/search_sbms_cluster.sh [gpu_id] , something wrong happened:

dgl._ffi.base.DGLError: Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device.

how can I run the code?

**Comment by phython96** [comment]
> when i try to run the sh scripts/search_sbms_cluster.sh [gpu_id] , something wrong happened:
> 
> dgl._ffi.base.DGLError: Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device.
> 
> how can I run the code?

which version of dgl do you use?

**Comment by ZhouAo-ZA** [comment]
> > when i try to run the sh scripts/search_sbms_cluster.sh [gpu_id] , something wrong happened:
> > dgl._ffi.base.DGLError: Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device.
> > how can I run the code?
> 
> which version of dgl do you use?


dgl-cu110                 0.6.1                    pypi_0    pypi

You may try dgl 0.4.2. 
Please refer to the file ["environment_gpu.yml"](https://github.com/graphdeeplearning/benchmarking-gnns/blob/master/environment_gpu.yml).
We use the same environment as the project benchmarking-gnns.

**Comment by ZhouAo-ZA** [comment]
thanks， I have solved this problem, it is just neet to move the graph to GPU, the latest dgl could also run.
