### ISSUE TITLE
About the search time is too long

### ISSUE THREAD

**Issue by ZhouAo-ZA** [phython96/GNAS-MP#2]
Thank you for your wonderful work, I find it very interesting!

I ran the **scripts/search_sbms_cluster.sh** directly on one V100 GPU, but I have searched for almost 12 hours and it is not over yet. This is too far from the 2.5 hours described in your article. I want to know whether it is necessary to set an early stop? Do I need to use multiple GPUs? I want to know your experimental hardware settings.

thanks！

**Comment by phython96** [comment]
> it



> Thank you for your wonderful work, I find it very interesting!
> 
> I ran the **scripts/search_sbms_cluster.sh** directly on one V100 GPU, but I have searched for almost 12 hours and it is not over yet. This is too far from the 2.5 hours described in your article. I want to know whether it is necessary to set an early stop? Do I need to use multiple GPUs? I want to know your experimental hardware settings.
> 
> thanks！

Yes, we found that the architecture tends to be stable after searching 10 epochs. 
You may try the searched GNN at 5 epoch or 10 epoch. 
We use a single RTX 2080Ti for search and train. 
Nevertheless, we also found that our code runs about as fast on the V100 as it does on the 2080TI.

**Comment by ZhouAo-ZA** [comment]
Is the architecture in the genotypes file the model you finally searched for? I used the gnn architecture on the original cluster data set in the genotypes  file to train and found that the test accuracy after 150 epochs was about 55%.

**Comment by phython96** [comment]
> Is the architecture in the genotypes file the model you finally searched for? I used the gnn architecture on the original cluster data set in the genotypes file to train and found that the test accuracy after 150 epochs was about 55%.

You may try "Adam" optimizer and see whether the issue is solved. 
If it still exists, we'll check it out when I'm free in a few days. 
Thank you for your issue.

**Comment by ZhouAo-ZA** [comment]
Thats right, I have tried the ADAM optimizer, it is about 60.5% accuracy in the end.
